trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - .azure/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: subscriptionService
    type: string 
    default: "AZURE_DEVOPS_SERVICE_CONNECTION"
  - name: subscriptionId
    type: string
    default: "$(subscriptionId)"

variables:
  - template: ../variables/common.yml
      
stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: ../variables/development.yml

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: ../steps/landingzone-infrastructure-steps.yml
            parameters:
              armPath: '${{ variables.armPath}}'
              subscriptionId: '${{ parameters.subscriptionId }}'
              subscriptionService: '${{ parameters.subscriptionService }}'
              rgName: '${{ variables.rgName}}'
              rgLocation: '${{ variables.rgLocation}}'
              appiName: '${{ variables.appiName}}'
              kvName: '${{ variables.kvName}}'
              stName: '${{ variables.stName}}'
              workName: '${{ variables.workName }}'
              workResourceGroupName: '${{ variables.workResourceGroupName }}'

  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: ../variables/production.yml

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: ../steps/landingzone-infrastructure-steps.yml
            parameters:
              armPath: '${{ variables.armPath}}'
              subscriptionId: '${{ parameters.subscriptionId }}'
              subscriptionService: '${{ parameters.subscriptionService }}'
              rgName: '${{ variables.rgName}}'
              rgLocation: '${{ variables.rgLocation}}'
              appiName: '${{ variables.appiName}}'
              kvName: '${{ variables.kvName}}'
              stName: '${{ variables.stName}}'
              workName: '${{ variables.workName }}'
              workResourceGroupName: '${{ variables.workResourceGroupName }}'