trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/Core/*
    - src/Infrastructure/*
    - src/Specs/*
    - src/Presentation/Functions/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: appcsEnvironmentVariable
    type: string 
    default: "AZURE_APPCS_CONNECTION_STRING_ENV_VAR"
  - name: appcsConnection
    type: string 
    default: "$(appcsConnection)" # from secrets (library)
  - name: subscriptionService
    type: string 
    default: "AZURE_DEVOPS_SERVICE_CONNECTION_NAME"

  - name: funcSettings
    type: object
    default: 
      - name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
        value: '$(appiKey)'
        slotSetting: false
      - name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
        value: '$(appiConnection)'
        slotSetting: false        
      - name: 'AZURE_FUNCTIONS_ENVIRONMENT'
        value: '$(rgEnvironment)'
        slotSetting: false
      - name: 'FUNCTIONS_EXTENSION_VERSION'
        value: '~$(funcVersion)'
        slotSetting: false
      - name: 'FUNCTIONS_WORKER_RUNTIME'
        value: '$(funcRuntime)'
        slotSetting: false

variables:
  - template: ../variables/common.yml

stages:
  - stage: development
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
    variables:
      - template: ../variables/development.yml

    jobs:
      - job: build_src
        steps:
          - template: ../steps/dotnet-build-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              srcPath: '$(srcPath)'

      - job: test_unit
        dependsOn: build_src
        steps:
          - template: ../steps/dotnet-test-steps.yml
            parameters:
              testPath: '$(unitPath)'
              testProject: '$(unitProject)'
              restorePath: '$(srcPath)'
              appcsEnvironmentVariable: '$(appcsEnvironmentVariable)'
              appcsConnection: '$(appcsConnection)'
              rgEnvironment: '$(rgEnvironment)'

      - job: build_func
        dependsOn: test_unit
        steps:
          - template: ../steps/func-build-steps.yml
            parameters:
              archiveFile: '$(archiveFileFunc)'
              scriptsPath: '$(scriptspath)'
              funcPath: '$(funcPath)'
              tempPath: '$(tempPath)'

      - job: settings_func
        dependsOn: build_func
        steps:
          - template: ../steps/func-settings-steps.yml
            parameters:
              subscriptionService: '${{ parameters.subscriptionService }}'              
              rgEnvironment: '$(rgEnvironment)'
              funcName: '$(funcName)'
              appSettings: '${{ parameters.funcSettings }}'

      - job: deploy_func
        dependsOn: settings_func
        steps:
          - template: ../steps/func-deploy-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              archiveFile: '$(archiveFileFunc)'
              funcName: '$(funcName)'
              subscriptionId: '$(subscriptionId)'
              subscriptionService: '${{ parameters.subscriptionService }}'
 
  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: ../variables/production.yml    

    jobs:
      - job: build_src
        steps:
          - template: ../steps/dotnet-build-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              srcPath: '$(srcPath)'

      - job: test_unit
        dependsOn: build_src
        steps:
          - template: ../steps/dotnet-test-steps.yml
            parameters:
              testPath: '$(unitPath)'
              testProject: '$(unitProject)'
              restorePath: '$(srcPath)'
              appcsEnvironmentVariable: '$(appcsEnvironmentVariable)'
              appcsConnection: '$(appcsConnection)'
              rgEnvironment: '$(rgEnvironment)'

      - job: build_func
        dependsOn: test_unit
        steps:
          - template: ../steps/func-build-steps.yml
            parameters:
              archiveFile: '$(archiveFileFunc)'
              scriptsPath: '$(scriptspath)'
              funcPath: '$(funcPath)'
              tempPath: '$(tempPath)'

      - job: settings_func
        dependsOn: build_func
        steps:
          - template: ../steps/func-settings-steps.yml
            parameters:
              subscriptionService: '${{ parameters.subscriptionService }}'              
              rgEnvironment: '$(rgEnvironment)'
              funcName: '$(funcName)'
              appSettings: '${{ parameters.funcSettings }}'

      - job: deploy_func
        dependsOn: settings_func
        steps:
          - template: ../steps/func-deploy-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              archiveFile: '$(archiveFileFunc)'
              funcName: '$(funcName)'
              subscriptionId: '$(subscriptionId)'
              subscriptionService: '${{ parameters.subscriptionService }}'