trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: apiSettings
    type: object
    default: 
      - name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
        value: '${{ variables.appiKey}}'
        slotSetting: false
      - name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
        value: '${{ variables.appiConnection}}'
        slotSetting: false        
      - name: 'AZURE_funcTIONS_ENVIRONMENT'
        value: '${{ variables.rgEnvironment}}'
        slotSetting: false
      - name: 'FUNCTIONS_EXTENSION_VERSION'
        value: '$(funcVersion)'
        slotSetting: false
      - name: 'FUNCTIONS_WORKER_RUNTIME'
        value: '$(funcRuntime)'
        slotSetting: false
      - name: '${{ variables.appcsEnvironmentVariable}}'
        value: '${{ variables.appcsConnection}}'
        slotSetting: false
      - name: '${{ variables.stEnvironmentVariable}}'
        value: '${{ variables.stConnection}}'
        slotSetting: false
  
variables:
  - template: ../variables/development.yml
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: ../variables/development.yml
      
    jobs:    
      - job: build_func
        steps:
          - template: ../steps/func-build-steps.yml
            parameters:
              archiveFile: '$(archiveFile)'
              funcPath: '${{ variables.funcPath}}'
              tempPath: '${{ variables.tempPath}}'

      - job: test_func
        dependsOn: build_func
        steps:
          - template: ../steps/dotnet-test-steps.yml
            parameters:
              unitPath: ${{ variables.funcPath}}
              rgEnvironment: '${{ variables.rgEnvironment}}'
              appcsEnvironmentVariable: '${{ variables.appcsEnvironmentVariable}}'
              appcsConnection: '${{ variables.appcsConnection}}'
              stEnvironmentVariable: '${{ variables.stEnvironmentVariable}}'
              stConnection: '${{ variables.stConnection}}'

      - job: settings_func
        dependsOn: build_func
        steps:
          - template: ../steps/func-settings-steps.yml
            parameters:
              subscriptionName: '$(subscriptionName)'
              rgEnvironment: '${{ variables.rgEnvironment}}'
              funcName: '${{ variables.funcName}}'
              appSettings: '${{ parameters.apiSettings }}'

      - job: deploy_func
        dependsOn: settings_func
        steps:
          - template: ../steps/func-deploy-steps.yml
            parameters:
              artifactsPath: '${{ variables.artifactsPath}}'
              archiveFile: '$(archiveFile)'
              funcName: '${{ variables.funcName}}'
              subscriptionId: '${{ variables.subscriptionId}}'
              subscriptionName: '$(subscriptionName)'

  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: ../variables/production.yml    

    jobs:    
      - job: build_func
        steps:
          - template: ../steps/func-build-steps.yml
            parameters:
              archiveFile: '$(archiveFile)'
              funcPath: '${{ variables.funcPath}}'
              tempPath: '${{ variables.tempPath}}'

      - job: test_func
        dependsOn: build_func
        steps:
          - template: ../steps/dotnet-test-steps.yml
            parameters:
              unitPath: ${{ variables.funcPath}}
              rgEnvironment: '${{ variables.rgEnvironment}}'
              appcsEnvironmentVariable: '${{ variables.appcsEnvironmentVariable}}'
              appcsConnection: '${{ variables.appcsConnection}}'
              stEnvironmentVariable: '${{ variables.stEnvironmentVariable}}'
              stConnection: '${{ variables.stConnection}}'

      - job: settings_func
        dependsOn: build_func
        steps:
          - template: ../steps/func-settings-steps.yml
            parameters:
              subscriptionName: '$(subscriptionName)'
              rgEnvironment: '${{ variables.rgEnvironment}}'
              funcName: '${{ variables.funcName}}'
              appSettings: '${{ parameters.apiSettings }}'

      - job: deploy_func
        dependsOn: settings_func
        steps:
          - template: ../steps/func-deploy-steps.yml
            parameters:
              artifactsPath: '${{ variables.artifactsPath}}'
              archiveFile: '$(archiveFile)'
              funcName: '${{ variables.funcName}}'
              subscriptionId: '${{ variables.subscriptionId}}'
              subscriptionName: '$(subscriptionName)'