trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - infrastructure/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: appcsKeys
    type: object
    default: [
      "MyCo:MyProduct:StorageTables:ConnectionString",
      "MyCo:MyProduct:ServiceBus:ConnectionString",
      "MyCo:MyProduct:FunctionUrl",
      "MyCo:MyProduct:FunctionCode",
      "MyCo:MyProduct:LinkBatchSize",
      "MyCo:MyProduct:HubName"
    ]
  - name: appcsValues
    type: object
    default: [
      "$(stConnection)",
      "$(sbConnection)",
      "https://$(funcName).azurewebsites.net",
      "$(funcCode)",
      "100",
      "$(hubName)"
    ]

variables:
  - template: variables/development.yml
  - name: buildPlatform
    value : 'Any CPU'
  - name: buildConfiguration
    value : 'Release'
        
stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/development.yml

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: steps/landingzone-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_appcs_infrastructure
        dependsOn: deploy_landing_zone
        steps:
          - template: steps/appcs-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appcsName: '$(appcsName)'
              appcsSku: '$(appcsSku)'              

      - job: deploy_appcs_settings
        dependsOn: deploy_appcs_infrastructure
        steps:
          - template: steps/appcs-settings-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionName: '$(subscriptionName)'
              subscriptionId: '$(subscriptionId)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appcsName: '$(appcsName)'
              appcsKeys: '${{ parameters.appcsKeys }}'
              appcsValues: '${{ parameters.appcsValues }}'

      - job: deploy_sb_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/sb-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              sbName: '$(sbName)'
              sbSku: '$(sbSku)'

      - job: deploy_func_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/func-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              appiKey: '$(appiKey) '
              appiConnection: '$(appiConnection)'
              funcName: '$(funcName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_webjob_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/webjob-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              planName: '$(planName)'
              webjobName: '$(webjobName)'

  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/production.yml

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: steps/landingzone-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_appcs_infrastructure
        dependsOn: deploy_landing_zone
        steps:
          - template: steps/appcs-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appcsName: '$(appcsName)'
              appcsSku: '$(appcsSku)'              

      - job: deploy_appcs_settings
        dependsOn: deploy_appcs_infrastructure
        steps:
          - template: steps/appcs-settings-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionName: '$(subscriptionName)'
              subscriptionId: '$(subscriptionId)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appcsName: '$(appcsName)'
              appcsKeys: '${{ parameters.appcsKeys }}'
              appcsValues: '${{ parameters.appcsValues }}'

      - job: deploy_sb_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/sb-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              sbName: '$(sbName)'
              sbSku: '$(sbSku)'

      - job: deploy_func_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/func-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              appiKey: '$(appiKey) '
              appiConnection: '$(appiConnection)'
              funcName: '$(funcName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_webjob_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/webjob-infrastructure-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              planName: '$(planName)'
              webjobName: '$(webjobName)'  
