trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: variables/development.yml
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: development
    condition: and(ne(variables['Build.SourceBranch'], 'refs/heads/main'), not(startsWith(variables['Build.SourceBranch'], 'refs/pull')), ne(variables['Build.Reason'], 'PullRequest'))
    variables:
      - template: variables/development.yml
      
    jobs:
      - job: build_src
        steps:
          - template: steps/src-build-steps.yml
            parameters:
              armPath: 'infrastructure'

      - job: test_src
        dependsOn: build_src
        steps:
          - template: steps/src-test-steps.yml
            parameters:
              armPath: 'infrastructure'
              unitPath: '$(System.DefaultWorkingDirectory)/src/filter'

      - job: build_func_filter
        dependsOn: test_src
        steps:
          - template: steps/func-filter-build-steps.yml
            parameters:
              armPath: 'infrastructure'

      - job: deploy_func_filter
        dependsOn: build_func_filter
        steps:
          - template: steps/func-filter-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'

      - job: deploy_logic_apps
        dependsOn: test_src
        steps:
          - template: steps/logic-filter-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'


  - stage: pull_request
    condition: or(eq(variables['Build.Reason'], 'PullRequest'),  startsWith(variables['Build.SourceBranch'], 'refs/pull'))
    variables:
      - template: variables/development.yml
      
    jobs:
      - job: test_src
        steps:
          - template: steps/src-test-steps.yml
            parameters:
              armPath: 'infrastructure'
              unitPath: '$(System.DefaultWorkingDirectory)/src/filter'

      - job: test_integration
        steps:
          - template: steps/integration-test-steps.yml
            parameters:
              armPath: 'infrastructure'

  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/production.yml    

    jobs:
      - job: build_src
        steps:
          - template: steps/src-build-steps.yml
            parameters:
              armPath: 'infrastructure'

      - job: test_src
        dependsOn: build_src
        steps:
          - template: steps/src-test-steps.yml
            parameters:
              armPath: 'infrastructure'
              unitPath: '$(System.DefaultWorkingDirectory)/src/filter'              

      - job: build_func_filter
        dependsOn: test_src
        steps:
          - template: steps/func-filter-build-steps.yml
            parameters:
              armPath: 'infrastructure'

      - job: deploy_func_filter
        dependsOn: build_func_filter
        steps:
          - template: steps/func-filter-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'

      - job: deploy_logic_apps
        dependsOn: test_src
        steps:
          - template: steps/logic-filter-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'

      - job: test_integration
        dependsOn: deploy_func_filter
        steps:
          - template: steps/integration-test-steps.yml
            parameters:
              armPath: 'infrastructure'