trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - tests/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: variables/development.yml
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: pull_request
    condition: startsWith(variables['Build.SourceBranch'], 'refs/pull')
    variables:
      - template: variables/development.yml
      
    jobs:
      - job: test_integration
        steps:
          - template: steps/integration-test-steps.yml
            parameters:
              armPath: 'infrastructure'
