trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: appcsEnvironmentVariable
    type: string 
    default: "AZURE_APP_CONFIGURATION_CONNECTION"
  - name: appcsConnection
    type: string 
    default: "${{ variables.appcsConnection}}" # from secrets (library)
  - name: subscriptionService
    type: string 
    default: "AZURE_DEVOPS_SERVICE_CONNECTION"

variables:
  - template: ../variables/common.yml

stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: ../variables/development.yml
      
    jobs:    
      - job: build_api
        steps:
          - template: ../steps/dotnet-build-steps.yml
            parameters:
              artifactsPath: '${{ variables.artifactsPath}}'
              srcPath: '${{ variables.srcPath}}'

      - job: test_api
        dependsOn: build_api
        steps:
          - template: ../steps/dotnet-test-steps.yml
            parameters:
              testPath: '$(System.DefaultWorkingDirectory)/src'
              appcsEnvironmentVariable: '${{ variables.appcsEnvironmentVariable}}'
              appcsConnection: '${{ variables.appcsConnection}}'
              rgEnvironment: '${{ variables.rgEnvironment}}'

      - job: deploy_api
        dependsOn: test_api
        steps:
          - template: ../steps/web-deploy-steps.yml
            parameters:
              appSettings: '-${{ variables.appcsEnvironmentVariable}} ${{ variables.appcsConnection}} -${{ variables.stEnvironmentVariable}} ${{ variables.stConnection}} -AzureWebJobsDashboard ${{ variables.stConnection}} -APPINSIGHTS_INSTRUMENTATIONKEY ${{ variables.appiKey}} -APPLICATIONINSIGHTS_CONNECTION_STRING ${{ variables.appiConnection}} -AZURE_FUNCTIONS_ENVIRONMENT ${{ variables.rgEnvironment}} -ASPNETCORE_ENVIRONMENT ${{ variables.rgEnvironment}} '
              artifactsPath: '${{ variables.artifactsPath}}'
              archiveFile: '${{ variables.archiveFile}}'
              webName: '${{ variables.apiName}}'
              subscriptionId: '${{ variables.subscriptionId}}'
              subscriptionService: '${{ parameters.subscriptionService}}'

  - stage: pull_request
    condition: eq(variables['Build.Reason'], 'PullRequest')
    variables:
      - template: ../variables/development.yml
      
    jobs:
      - job: test_src
        steps:
          - template: ../steps/src-test-steps.yml
            parameters:
              armPath: '${{ variables.armPath}}'

      - job: test_integration        
        dependsOn: test_src
        steps:
          - template: ../steps/integration-test-steps.yml
            parameters:
              armPath: '${{ variables.armPath}}'

  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: ../variables/production.yml    

    jobs:    
      - job: build_api
        steps:
          - template: ../steps/dotnet-build-steps.yml
            parameters:
              artifactsPath: '${{ variables.artifactsPath}}'
              srcPath: '${{ variables.srcPath}}'

      - job: test_api
        dependsOn: build_api
        steps:
          - template: ../steps/dotnet-test-steps.yml
            parameters:
              testPath: '$(System.DefaultWorkingDirectory)/src'
              appcsEnvironmentVariable: '${{ variables.appcsEnvironmentVariable}}'
              appcsConnection: '${{ variables.appcsConnection}}'
              rgEnvironment: '${{ variables.rgEnvironment}}'

      - job: deploy_api
        dependsOn: test_api
        steps:
          - template: ../steps/web-deploy-steps.yml
            parameters:
              appSettings: '-${{ variables.appcsEnvironmentVariable}} ${{ variables.appcsConnection}} -${{ variables.stEnvironmentVariable}} ${{ variables.stConnection}} -AzureWebJobsDashboard ${{ variables.stConnection}} -APPINSIGHTS_INSTRUMENTATIONKEY ${{ variables.appiKey}} -APPLICATIONINSIGHTS_CONNECTION_STRING ${{ variables.appiConnection}} -AZURE_FUNCTIONS_ENVIRONMENT ${{ variables.rgEnvironment}} -ASPNETCORE_ENVIRONMENT ${{ variables.rgEnvironment}} '
              artifactsPath: '${{ variables.artifactsPath}}'
              archiveFile: '${{ variables.archiveFile}}'
              webName: '${{ variables.apiName}}'
              subscriptionId: '${{ variables.subscriptionId}}'
              subscriptionService: '${{ parameters.subscriptionService}}'