parameters:
  - name: subscriptionService
    type: string 
    default: 'COMPANY-PRODUCT-001'
  - name: rgEnvironment
    type: string 
    default: 'Development'
  - name: apiName
    type: string 
    default: "api-PRODUCT-ENVIRONMENT-001"
  - name: appSettings
    type: object
    default: 
      - name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
        value: '${{ variables.appiKey}}'
        slotSetting: false
      - name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
        value: '${{ variables.appiConnection}}'
        slotSetting: false        
      - name: 'ASPNETCORE_ENVIRONMENT'
        value: '${{ variables.rgEnvironment}}'
        slotSetting: false
      - name: '${{ variables.appcsEnvironmentVariable}}'
        value: '${{ variables.appcsConnection}}'
        slotSetting: false
      - name: '${{ variables.stEnvironmentVariable}}'
        value: '${{ variables.stConnection}}'
        slotSetting: false

steps:
  - ${{ each appSetting in parameters.appSettings }}:
    - task: AzureAppServiceSettings@1
      displayName: 'set_appsettings ${{ appSetting.name }}'
      inputs:
        azureSubscription: ${{ parameters.subscriptionService }}
        appName: ${{ parameters.apiName }}    
        appSettings: |
          [
            {
              "name": "${{ appSetting.name }}",
              "value": "${{ appSetting.value }}",
              "slotSetting": "${{ appSetting.slotSetting }}"
            }
          ]
        slotName: ${{ parameters.slotName }}